In [1]:
import numpy as np 

In [12]:
def find_det(A, total = 0):
    dim = A.shape[0]
    
    if dim == 2:
        det = A[0,0]*A[1,1] - A[1,0]*A[0,1]
        return det
    else:
        A1 = A.copy()
        A1 = np.delete(A1,0,0) # delete the first row
        cols =  A.shape[1]
        
        for i in range(cols):
         # delete the column corresponding to the position of the element traversed

            A2 = np.delete(A1,i,1)
            total += (-1)**i + A[0,i] * find_det(A2)
        return total
    

In [13]:
def crammer(A, b):
    
    n = A.shape[0]
    X = np.zeros((n))
    
    D = find_det(A)
    
    for i in range(n):
        
        Ai = A.copy()
        Ai[:,i] = b
        
        Di = find_det(Ai)
        
        X[i] = Di/D
    
    return X

In [14]:
A = np.array([[1,1,0,3],
            [2,1,-1,1],
            [3,-1,-1,2],
            [-1,2,3,-1]])

b = np.array([4,1,-3,4])

print(A)
print(b)

[[ 1  1  0  3]
 [ 2  1 -1  1]
 [ 3 -1 -1  2]
 [-1  2  3 -1]]
[ 4  1 -3  4]


In [15]:
crammer(A, b)

array([-5.25, -8.5 , 11.75,  5.25])

In [16]:
np.linalg.solve(A,b)

array([-1.00000000e+00,  2.00000000e+00, -7.40148683e-17,  1.00000000e+00])