In [1]:
import numpy as np

def polynomial(m,n,t,c):
    A = np.empty((m,n))
    for i in range(m):
        for j in range(n):
            A[i,j] = t[i]**(n)
    return A@c

In [2]:
np.empty((3,2))

array([[2.1749497e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

In [3]:
m, n = 10, 8
t = np.random.randint(0, 100, m)
t

array([23, 93, 99,  2, 96,  1, 82, 98, 26, 11])

In [4]:
c = np.random.randint(0, 100,  n)
c

array([92, 98, 83, 36, 28, 13, 89, 32])

In [5]:
polynomial(m, n, t, c)

array([3.68844741e+13, 2.63563032e+18, 4.34612751e+18, 1.20576000e+05,
       3.39774492e+18, 4.71000000e+02, 9.62790344e+17, 4.00709384e+18,
       9.83575474e+13, 1.00963033e+11])